### ISSUE TITLE
package.yml checken

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/linter#3]
z.B. Mit https://github.com/romaricdrigon/MetaYaml

**Comment by staabm** [comment]
bsp yaml

```yml
package: minibar
version: '1.0.10-dev'
author: 'Friends Of REDAXO'
supportpage: https://github.com/FriendsOfREDAXO/minibar

requires:
    redaxo: ^5.7.0
    php:
        version: '^7.1'
```

bsp schema
```yml
root: # root is always required (note no prefix here)
  _type: array # each element must always have a '_type'
  _ignore_extra_keys: true
  _children: # array nodes have a '_children' node, defining their children
    package:
      _type: text
      _required: true
    version:
      _type: text
      _required: true
    author:
      _type: text
    supportpage:
      _type: text
    perm:
      _type: text

    page:
      _type: partial
      _partial: partial_page

    requires:
      _type: array
      _ignore_extra_keys: true
      _children:
        redaxo:
          _type: partial
          _partial: partial_version_def
        php:
          _type: array
          _ignore_extra_keys: true
          _children:
              version:
                _type: partial
                _partial: partial_version_def

    conflicts:
      _type: array
      _ignore_extra_keys: true
      _children:
        redaxo:
          _type: partial
          _partial: partial_version_def
        php:
          _type: array
          _ignore_extra_keys: true
          _children:
            version:
              _type: partial
              _partial: partial_version_def

partials:
  partial_page:
    _type: array
    _ignore_extra_keys: true
    _children:
      title:
        _type: text
      icon:
        _type: text
      perm:
        _type: text
      subPath:
        _type: text
      subpages:
        _type: prototype
        _prototype:
          _type: partial
          _partial: partial_page
  partial_version_def:
    _type: text
```
